[package]
name = "keyboard-linux"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
vietnamese-core = { path = "../vietnamese-core" }
xkeysym.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
x11rb.workspace = true
xkbcommon.workspace = true

[dev-dependencies]
unicode-segmentation.workspace = true
