[package]
name = "keyboard-linux"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
vietnamese-core = { path = "../vietnamese-core" }
xkeysym.workspace = true
libc.workspace = true
x11rb.workspace = true
xkbcommon.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
unicode-segmentation.workspace = true
