[package]
name = "vietnamese-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
unicode-normalization.workspace = true
unicode-segmentation.workspace = true

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "process_key"
harness = false

